/**
 * TTN — original analysis articles
 * These are written in-house (not aggregated from RSS), so unlike the
 * news feed, the full text lives here and can be shown on-site directly.
 */
const TTN_ARTICLES = [
  {
    id: "fed-policy-2026",
    title: "How Fed Policy Shifts Ripple Through Stocks, Bonds, and Crypto",
    dek: "A look at why interest-rate decisions move nearly every asset class TTN tracks, and how to read the signals.",
    author: "TTN Research Desk",
    date: "2026-07-15",
    tickers: ["S&P 500", "NASDAQ", "BTC"],
    body: [
      "Interest rate decisions from the Federal Reserve are one of the few events that reliably move stocks, bonds, gold, and crypto on the same day. Eight times a year, the Federal Open Market Committee meets to decide whether to raise, cut, or hold the federal funds rate. Traders don't just react to the decision itself; they react to the wording of the statement and the tone of the press conference that follows. Understanding the underlying mechanism helps explain why markets can swing several percent on what looks, on paper, like a fairly technical announcement.",
      "The core idea is the 'discount rate,' which is how future cash flows get translated into a present-day value. Every stock, bond, and even many crypto valuation models rely on some version of this math: an asset's price today reflects the cash or value it's expected to generate in the future, discounted back by a rate that reflects the time value of money and risk. When the Fed raises rates, that discount rate goes up across the board, which mechanically lowers the present value of future cash flows, even if a company's actual business hasn't changed at all overnight.",
      "This is why growth-oriented stocks, the kind that make up a large share of the Nasdaq, are especially sensitive to rate decisions. A company expected to generate most of its profit five or ten years from now has cash flows that get discounted much more heavily than a company generating steady profit today. That's typically why tech-heavy indices swing more than broader benchmarks like the S&P 500 around Fed meetings, and why 'high growth, low current profit' stocks tend to underperform sharply in rate-hiking cycles.",
      "Bonds react even more directly, since the Fed's rate decision essentially sets the floor for short-term borrowing costs across the economy. When the Fed raises rates, newly issued bonds pay more interest, which makes existing bonds, locked in at the old, lower rate, less attractive, so their market price falls. This inverse relationship between rates and bond prices is one of the most consistent mechanical links in finance: bond prices and yields move in opposite directions, almost by definition. Longer-dated bonds are more sensitive to this than short-dated ones, because a rate change affects more years of future interest payments.",
      "Gold's relationship with rates is more indirect, and runs through something called the 'real interest rate,' which is the nominal rate minus inflation. Since gold pays no yield of its own, it competes with interest-bearing assets like bonds and cash. When real rates are high, holding gold means giving up meaningful interest income elsewhere, which can pressure prices. When real rates are low or negative, meaning inflation is outpacing what savers earn on cash, gold becomes relatively more attractive, since it isn't losing purchasing power to inflation the way idle cash is. This is a more precise way to think about gold's rate sensitivity than just 'rates up, gold down,' which doesn't always hold in practice.",
      "Crypto's link to Fed policy has strengthened noticeably over the past several years, as more institutional capital has entered the space. Bitcoin and Ethereum increasingly trade like risk assets, rallying on dovish signals such as rate cuts, pauses, or softer inflation data, and selling off on hawkish surprises, similar to how growth stocks behave, though usually with larger swings in either direction. Part of this is liquidity-driven: when borrowing is cheap and money is flowing freely through the financial system, some of that capital finds its way into higher-risk, higher-reward assets, crypto included. When the Fed tightens and that liquidity dries up, the same flows tend to reverse.",
      "It's worth being careful not to overstate the relationship, though. Crypto markets are also driven by factors that have nothing to do with US monetary policy, including regulatory news, exchange-specific events, on-chain developments, and shifts in retail sentiment, all of which can move prices independently of what the Fed is doing. The correlation with Fed policy is real and has grown stronger, but it isn't the only force at work, and treating Bitcoin as simply 'a leveraged Nasdaq trade' oversimplifies a market that still has its own distinct dynamics.",
      "For anyone tracking TTN's ticker strip, the practical takeaway is this: Fed announcement days are when correlations across very different assets, such as a tech stock, a Treasury bond, a gold ETF, and Bitcoin, can suddenly move in the same direction, because they're all repricing off the same discount-rate and liquidity assumptions at once. That's worth watching if you hold a mix of these assets for diversification, since the benefit of holding uncorrelated assets can shrink exactly when you need it most, during the kind of broad market stress that often follows a surprise Fed move.",
    ],
  },
  {
    id: "bitcoin-halving-cycles",
    title: "What Bitcoin's Halving Cycles Actually Tell Us, and What They Don't",
    dek: "Bitcoin's supply schedule is one of the most-discussed patterns in crypto. Here's what the historical pattern shows, and where the theory runs into limits.",
    author: "TTN Research Desk",
    date: "2026-06-28",
    tickers: ["BTC", "ETH"],
    body: [
      "Roughly every four years, Bitcoin's block reward, the amount of new BTC paid to miners for confirming transactions, is cut in half. This 'halving' is written directly into Bitcoin's code and happens automatically after every 210,000 blocks are mined, based purely on block count rather than a calendar date or market conditions. It's one of the few genuinely predictable, non-negotiable events in an otherwise famously unpredictable market.",
      "The mechanics are straightforward. Bitcoin launched with a block reward of 50 BTC. The first halving cut that to 25, the second to 12.5, the third to 6.25, and so on, each event permanently reducing the rate at which new bitcoin enters circulation. This continues until the reward effectively rounds to zero, expected sometime around the year 2140, at which point no new bitcoin will be created and miners will rely entirely on transaction fees for revenue. The total supply is capped at 21 million coins, and the halving schedule is the mechanism that enforces that cap gradually rather than all at once.",
      "The pattern that gets the most attention from traders is this: in Bitcoin's history so far, price has tended to rise substantially in the 12 to 18 months following a halving. The simple explanation is supply and demand. New coin issuance drops sharply overnight while demand, at least historically, kept growing or held steady, and reduced new supply hitting the market can support price if buying pressure stays constant or increases. This logic has been popularized under the name 'stock-to-flow,' a model that attempts to predict Bitcoin's price based on the ratio of existing supply to new issuance, drawing a loose analogy to how scarcity has historically supported the value of gold and other commodities.",
      "But it's worth being precise about what this pattern does and doesn't prove, and where the stock-to-flow style reasoning runs into trouble. Bitcoin has only had four halvings as of 2026, which is a very small sample size to draw firm conclusions from. Four data points isn't nearly enough to call something a reliable law of markets, no matter how clean the chart looks in hindsight. Statisticians would call this overfitting: finding a pattern that explains past data well but has little genuine predictive power, because there simply hasn't been enough independent data to test it properly.",
      "Each halving also happened alongside other major shifts that had nothing to do with the halving mechanism itself, including growing institutional adoption, the launch of spot Bitcoin ETFs, evolving regulatory frameworks in major economies, macroeconomic cycles, and shifts in global liquidity conditions. Untangling how much of any post-halving rally came from reduced supply versus these other, larger forces is genuinely difficult, and probably impossible to do with real statistical confidence. It's entirely possible that halvings coincided with rallies driven mainly by unrelated adoption cycles, rather than causing those rallies directly.",
      "There's also a case, grounded in basic market theory, that markets are efficient enough by now to have priced in a scheduled, publicly known event well in advance. A halving isn't a surprise. The exact block height at which it will occur has been known for years, so in theory its effects on supply should already be reflected in the price before it happens, at least partially, as forward-looking traders position themselves ahead of time rather than waiting for the event itself. If that's true, the 'halving pump' narrative may be partly a story that gets told after the fact to explain a rally that had other causes.",
      "It's also worth noting what halvings do to the mining industry itself, since this is often overlooked in price-focused discussions. A sudden 50% cut to block rewards can squeeze the profitability of mining operations, particularly smaller or less efficient ones, sometimes forcing consolidation or temporary drops in network hash rate until the difficulty adjustment mechanism rebalances things. This is a real, structural effect of halvings that's separate from, and arguably more certain than, any price prediction.",
      "One more angle worth considering is how halvings interact with broader Bitcoin adoption cycles rather than acting in isolation. Each halving so far has landed at a different stage of the asset's maturity. The 2012 halving happened when Bitcoin was still a niche experiment with minimal liquidity, while the most recent halvings occurred alongside spot ETF approvals, corporate treasury adoption, and vastly deeper institutional market infrastructure. Comparing price reactions across these very different market environments as if they were repeated trials of the same experiment is part of what makes the stock-to-flow style analysis less reliable than it first appears, since the conditions surrounding each halving have never actually been held constant.",
      "The honest summary is this: halvings are a real, mechanical, verifiable change to Bitcoin's supply issuance, and the historical correlation with subsequent price increases is genuinely worth knowing as part of the broader picture. But treating it as a guaranteed formula, where a halving happens and price simply quadruples, ignores both the small sample size behind that pattern and the many other, often larger, forces moving crypto markets at the same time. A useful frame is to think of the halving as one input among many, not a standalone trading signal.",
    ],
  },
  {
    id: "gold-hedge-explainer",
    title: "Is Gold Still a Hedge? What the Metal Actually Protects Against",
    dek: "Gold's reputation as a 'safe haven' gets repeated often, but a hedge against what, exactly? Breaking down the three scenarios where gold tends to hold up.",
    author: "TTN Research Desk",
    date: "2026-06-10",
    tickers: ["GOLD", "EUR/USD"],
    body: [
      "\"Gold is a hedge\" is one of the most repeated lines in finance, but it's rarely explained what it's actually a hedge against. Gold doesn't behave like a single, uniform 'safe asset.' It responds to different economic pressures in different ways, and lumping all of that under one vague label makes it harder to use the metal sensibly in a portfolio. There are three distinct scenarios worth separating, plus a few situations where gold's reputation doesn't hold up as well as its marketing suggests.",
      "The first scenario is inflation. Because gold can't be printed or created by a central bank, it has historically held purchasing power over very long time horizons better than cash sitting in a low-yield account. This doesn't mean gold rises every time a monthly inflation report comes in hot. Short-term correlation between gold and inflation prints is genuinely inconsistent, and gold can sit flat or even fall in months when inflation is rising, especially if real interest rates are moving in the opposite direction at the same time. But over multi-decade horizons, gold has generally kept pace with or outpaced inflation, which is a meaningfully different and more defensible claim than 'gold hedges inflation on any given day.'",
      "This connects to a more precise concept: the real interest rate, which is the nominal interest rate minus the inflation rate. Gold pays no yield of its own, so it's constantly competing against interest-bearing assets like Treasury bonds and savings accounts. When real rates are high, meaning investors can earn a solid return after accounting for inflation, holding non-yielding gold carries a real opportunity cost, which tends to pressure prices. When real rates are low or negative, as they were for extended stretches in recent years, that opportunity cost shrinks or disappears, and gold tends to become relatively more attractive. Watching real rates, not just headline inflation, is a more reliable way to think about gold's inflation-hedge behavior.",
      "The second scenario is currency weakness. Gold is priced in US dollars globally, so when the dollar weakens against other major currencies, gold often becomes cheaper for foreign buyers in their own local currency terms, which can support demand and push the dollar price higher. This is one reason gold and the US Dollar Index frequently move in opposite directions, and it's part of why gold-watchers also keep an eye on major currency pairs like EUR/USD. A weakening dollar story and a strengthening gold story often arrive together, even though they're driven by related but distinct mechanisms.",
      "The third scenario, and the one gold is best known for, is crisis demand, sometimes called 'flight to safety.' During periods of acute financial stress, geopolitical conflict, banking instability, or sudden shocks to investor confidence, gold tends to see a bid as investors move capital out of riskier assets like stocks and into something perceived as holding value independent of any single government or financial institution. This is the scenario where gold's 'safe haven' reputation is most consistently earned, and it's also visible in central bank behavior. Many central banks around the world have been steady net buyers of gold in recent years, partly as a hedge against geopolitical and currency risk in their own reserve holdings.",
      "What gold is not particularly good at is protecting against ordinary, garden-variety stock market volatility. It doesn't reliably rise every time equities fall on a normal down day. Plenty of routine market pullbacks happen with gold moving sideways or even declining alongside stocks, particularly if the same event, like rising rates, is pressuring both asset classes at once. Investors who expect gold to smooth out every dip in their equity portfolio are often disappointed, because gold's protective behavior tends to show up specifically during the less frequent, more severe stress events rather than everyday volatility.",
      "It's also worth briefly addressing the comparison to Bitcoin, sometimes marketed as 'digital gold.' Both are non-yielding, supply-constrained assets that some investors use as an inflation or currency hedge. But they behave quite differently in practice. Gold has centuries of trading history and tends to be far less volatile, while Bitcoin has shown a much stronger tendency in recent years to trade like a high-beta risk asset, particularly around Fed policy decisions, rather than a defensive one. Treating the two as interchangeable hedges overstates how similarly they actually behave.",
      "Taken together, treating gold as a hedge against inflation, currency risk, and acute financial crises, rather than a hedge against everything including everyday market noise, is a more accurate and more useful way to think about its role in a portfolio. It's a tool suited to specific jobs, not a universal insurance policy.",
    ],
  },
];
